---
- name: Deploy archive | Update pkg manager cache
  ansible.builtin.package:
    update_cache: true

- name: Deploy archive | Install dependencies (unzip)
  ansible.builtin.package:
    name: unzip
    state: present
