---
- name: Deploy archive | Include setup_asset.yml
  ansible.builtin.include_tasks: setup_asset.yml

- name: Deploy archive | Include crontab.yml
  ansible.builtin.include_tasks: crontab.yml
  when: deploy_archive_cron is defined

- name: Deploy archive | Include systemd.yml
  ansible.builtin.include_tasks: systemd.yml
  when: deploy_archive_systemd_content is defined
