---
- name: Deploy archive | Setup systemd file
  ansible.builtin.copy:
    content: "{{ deploy_archive_systemd_content }}"
    dest: "/etc/systemd/system/{{ deploy_archive_app_name }}.service"
    mode: "0644"
  notify: "Daemon reload service"

- name: Deploy archive | Restart systemd service
  ansible.builtin.debug:
    msg: "trigger {{ deploy_archive_app_name }} restart"
  notify: Restart systemd service
  changed_when: true
  when: deploy_archive_systemd_restart is true
