---
- name: Daemon reload service
  ansible.builtin.systemd:
    name: "{{ deploy_archive_app_name }}"
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart systemd service
  ansible.builtin.systemd:
    name: "{{ deploy_archive_app_name }}"
    state: restarted
  when: "(deploy_archive_app_name.service) in ansile_facts.services"
