---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cron
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
  - name: systemd
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      cron:
        deploy_archive_cron:
          {
            day: "*",
            hour: "20",
            minute: "58",
            job: "python3 {{ deploy_archive_dest }}/{{ deploy_archive_app_name}}.py --conf {{ deploy_archive_dest }}/{{ deploy_archive_conf.filename }}"
          }
      systemd:
        deploy_archive_systemd_content: |
          "[Unit]
          Description=Some systemd for {{ deploy_archive_app_name }} service
          After=network.target

          [Service]
          Type=simple
          ExecStart= echo "hello-world"
          Restart=always
          User={{ deploy_archive_user.name }}
          Group={{ deploy_archive_user.group }}

          [Install]
          WantedBy=multi-user.target"
verifier:
  name: ansible
